---
- name: Check Status
  hosts: node1
  become: true
  gather_facts: no
  vars:
    package: 
      - httpd
      - sshd

  tasks:
    - name: Check status of {{ package }} service
      ansible.builtin.service_facts:
      register: service_state

    - ansible.builtin.debug:
        var: service_state.ansible_facts.services["{{ item }}.service"].state
      with_items:
        - "{{ package }}"
