- name: get facts
  hosts: all
 
- name: cp files 
  hosts: node2
  become: true
  tasks:
    - name: cp hosts
      template:
        src: ./hosts.j2
        dest: /etc/hosts.bak
    - debug:
        var: hostvars
