- name: Hwreport
  hosts: all
  tasks:
    - name: Init file
      copy:
        content: "hostname: inventoryhostname \nmem: memory_in_MB \nbios: BIOS_version \nvda: disk_vda_size \nvdb: disk_vdb_size\n"
        dest: /root/hwreport.txt

    - name: Get hostname
      replace:
        path: /root/hwreport.txt
        regexp: 'inventoryhostname'
        replace: "{{ ansible_hostname }}"

    - name: Get memory_in_MB
      replace:
        path: /root/hwreport.txt
        regexp: 'memory_in_MB'
        replace: "{{ ansible_memtotal_mb }}"

    - name: Get BIOS
      replace:
        path: /root/hwreport.txt
        regexp: 'BIOS_version'
        replace: "{{ ansible_bios_version }}"

    - name: Get disk_vda_size
      replace:
        path: /root/hwreport.txt
        regexp: 'disk_vda_size'
        replace: "{{ ansible_devices.sda.size | default('NONE',true) }}"

    - name: Get disk_vdb_size
      replace:
        path: /root/hwreport.txt
        regexp: 'disk_vdb_size'
        replace: "{{ ansible_devices.sdb.size | default('NONE',true) }}"
