---
- name: Check Status
  hosts: node1
  become: true
  vars:
    package:
      - "httpd"
      - "sshd"

  tasks:
    - name: Check status of {{ package }} service
      ansible.builtin.service_facts:
      register: service_state
      loop:
        - "{{ package }}"

    - ansible.builtin.debug:
        var: service_state.ansible_facts.services["{{ package }}.service"].state
      loop:
        - "{{ package }}"